title: Valley Share
description: ""
url: "" # 例如 https://<username>.github.io
baseurl: "" # 例如 /repo-name （个人主页留空）
lang: zh-CN

author:
  name: valley team
  email: valley-team@bytedance.net

# Markdown 处理器配置
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  enable_coderay: false
  tables: true
  auto_ids: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  hard_wrap: false
  # 自动识别URL和邮箱链接
  parse_block_html: true
  parse_span_html: true

# GitHub Pages 支持的插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 6
paginate_path: "/page:num"

theme: null  # 使用自定义主题（本仓库的布局与样式）

# 站点导航
nav:
  - title: Home
    url: /
  - title: Tags
    url: /tags/
  - title: About us
    url: /about/

# 社交/统计（可选）
google_analytics: ""  # UA-XXXX 或 G-XXXX；留空则不加载
